---
- name: Repos | Update the sources list (/etc/apt/sources.list)
  template:
    src: "{{ ansible_distribution }}.sources.list.j2"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: Repos | Update the apt cache
  apt:
    update_cache: yes

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: "{{ item.key }}"
    state: present
  with_items:
    - "{{ apt_repos_list }}"

- name: Add an Apt repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
  with_items:
    - "{{ apt_repos_list }}"

- name: Repos | Update the apt cache
  apt:
    update_cache: yes
