---
- name: Apt | Update the sources list (/etc/apt/sources.list)
  template:
    src: "{{ ansible_distribution }}.sources.list.j2"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: Apt | Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: "{{ item.key }}"
    state: present
    keyring: "{{ item.keyring | default(omit) }}"
  with_items:
    - "{{ apt_repos_list }}"

- name: Apt | Add an Apt repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
    update_cache: no
  with_items:
    - "{{ apt_repos_list }}"

- name: Apt | Add the Debian Security repository
  apt_repository:
    repo: "deb http://security.debian.org/ {{ ansible_distribution_release }}/updates main"
    state: present
    filename: security
    update_cache: no
  when: ansible_distribution == 'Debian'

- name: Apt | Update the apt cache
  apt:
    update_cache: yes
