---
- include_tasks: apt_repos.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - repos

- include_tasks: yum_repos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  tags:
    - repos

- include_tasks: apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - apt
    - pkg

- include_tasks: yum.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  tags:
    - yum
    - pkg

- include_tasks: limits.yml
  tags:
    - ulimit

- include_tasks: locales.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - locales

- include_tasks: profile.yml
  tags:
    - profile
